R"(res/foo.png
res/foo1.png
res/foo10.png
res/foo11.png
res/foo12.png
res/foo2.png
res/foo3.png
res/foo4.png
res/foo5.png
res/foo6.png
res/foo7.png
res/foo8.png
res/foo9.png
res/hands.png
res/image.bmp
res/pencil.png
res/Roboto-Black.ttf
res/Roboto-BlackItalic.ttf
res/Roboto-Bold.ttf
res/Roboto-BoldItalic.ttf
res/Roboto-Italic.ttf
res/Roboto-License.txt
res/Roboto-Light.ttf
res/Roboto-LightItalic.ttf
res/Roboto-Medium.ttf
res/Roboto-MediumItalic.ttf
res/Roboto-Regular.ttf
res/Roboto-Thin.ttf
res/Roboto-ThinItalic.ttf
)"